import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker from '../worker/index';
const env={ASSETS:{fetch:async()=>new Response('asset')},QUOTES_ENABLED:'true',RESEND_API_KEY:'test',TURNSTILE_SECRET_KEY:'test',TURNSTILE_HOSTNAME:'example.com',MAIL_FROM:'test@example.com',CONTACT_TO:'owner@example.com'};
function req(overrides:Record<string,string>={},photo?:File){const data=new FormData();Object.entries({name:'Test customer',phone:'0751382897',email:'test@example.com',city:'Montreuil',service:'electricity',description:'A new electrical installation',consent:'yes','cf-turnstile-response':'test-token',...overrides}).forEach(([k,v])=>data.set(k,v));if(photo)data.append('photos',photo);return new Request('https://example.com/api/quote',{method:'POST',headers:{Origin:'https://example.com'},body:data});}
test('fails closed before configuration',async()=>assert.equal((await worker.fetch(req(),{...env,QUOTES_ENABLED:'false'})).status,503));
test('rejects foreign origins',async()=>{const r=req();r.headers.set('Origin','https://evil.example');assert.equal((await worker.fetch(r,env)).status,403);});
test('rejects unsupported services and missing consent',async()=>{assert.equal((await worker.fetch(req({service:'unsupported'}),env)).status,400);assert.equal((await worker.fetch(req({consent:''}),env)).status,400);});
test('rejects excessive payload before parsing',async()=>{const r=req();r.headers.set('Content-Length',String(11*1024*1024));assert.equal((await worker.fetch(r,env)).status,413);});
test('does not email when Turnstile fails',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({success:false});};try{assert.equal((await worker.fetch(req(),env)).status,403);assert.equal(calls,1);}finally{globalThis.fetch=original;}});
test('rejects wrong Turnstile host and disguised images',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({success:true,hostname:'evil.example',action:'quote'});assert.equal((await worker.fetch(req(),env)).status,403);globalThis.fetch=async()=>Response.json({success:true,hostname:'example.com',action:'quote'});assert.equal((await worker.fetch(req({},new File(['not an image'],'x.jpg',{type:'image/jpeg'})),env)).status,400);}finally{globalThis.fetch=original;}});
test('sends validated email attachment and reports provider failure honestly',async()=>{const original=globalThis.fetch;let email:any;try{globalThis.fetch=async(url,init)=>{if(String(url).includes('siteverify'))return Response.json({success:true,hostname:'example.com',action:'quote'});email=JSON.parse(String(init?.body));return Response.json({id:'mock-id'});};const photo=new File([new Uint8Array([255,216,255,0])],'photo.jpg',{type:'image/jpeg'});assert.equal((await worker.fetch(req({},photo),env)).status,200);assert.equal(email.reply_to,'test@example.com');assert.equal(email.attachments[0].filename,'photo-1.jpg');globalThis.fetch=async url=>String(url).includes('siteverify')?Response.json({success:true,hostname:'example.com',action:'quote'}):new Response('',{status:500});assert.equal((await worker.fetch(req(),env)).status,502);}finally{globalThis.fetch=original;}});
