import {test} from 'node:test';
import assert from 'node:assert/strict';
import worker from '../worker/handler';
const env={ASSETS:{fetch:async()=>new Response('asset')},QUOTES_ENABLED:'true',EMAIL:{send:async()=>{}},QUOTE_LIMITS:{getByName:()=>({reserve:async()=>({ok:true})})},TURNSTILE_SECRET_KEY:'test',TURNSTILE_HOSTNAME:'example.com',MAIL_FROM:'test@example.com',CONTACT_TO:'cristian.sandu.connect@gmail.com'};
function req(overrides:Record<string,string>={},photo?:File){const data=new FormData();Object.entries({name:'Test customer',phone:'0751382897',email:'test@example.com',city:'Montreuil',service:'electricity',description:'A new electrical installation',consent:'yes','cf-turnstile-response':'test-token',...overrides}).forEach(([k,v])=>data.set(k,v));if(photo)data.append('photos',photo);return new Request('https://example.com/api/quote',{method:'POST',headers:{Origin:'https://example.com','CF-Connecting-IP':'192.0.2.1'},body:data});}
test('fails closed before configuration',async()=>assert.equal((await worker.fetch(req(),{...env,QUOTES_ENABLED:'false'} as any)).status,503));
test('rejects foreign origins',async()=>{const r=req();r.headers.set('Origin','https://evil.example');assert.equal((await worker.fetch(r,env as any)).status,403);});
test('rejects unsupported services and missing consent',async()=>{assert.equal((await worker.fetch(req({service:'unsupported'}),env as any)).status,400);assert.equal((await worker.fetch(req({consent:''}),env as any)).status,400);});
test('rejects excessive payload before parsing',async()=>{const r=req();r.headers.set('Content-Length',String(11*1024*1024));assert.equal((await worker.fetch(r,env as any)).status,413);});
test('does not email when Turnstile fails',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({success:false});};try{assert.equal((await worker.fetch(req(),env as any)).status,403);assert.equal(calls,1);}finally{globalThis.fetch=original;}});
test('rejects wrong Turnstile host and disguised images',async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>Response.json({success:true,hostname:'evil.example',action:'quote'});assert.equal((await worker.fetch(req(),env as any)).status,403);globalThis.fetch=async()=>Response.json({success:true,hostname:'example.com',action:'quote'});assert.equal((await worker.fetch(req({},new File(['not an image'],'x.jpg',{type:'image/jpeg'})),env as any)).status,400);}finally{globalThis.fetch=original;}});
test('sends only to the fixed recipient and reports provider failure',async()=>{const original=globalThis.fetch;let email:any;try{globalThis.fetch=async()=>Response.json({success:true,hostname:'example.com',action:'quote'});const sending={...env,EMAIL:{send:async(message:any)=>{email=message;}}};const photo=new File([new Uint8Array([255,216,255,0])],'photo.jpg',{type:'image/jpeg'});assert.equal((await worker.fetch(req({},photo),sending as any)).status,200);assert.equal(email.to,'cristian.sandu.connect@gmail.com');assert.equal(email.replyTo,'test@example.com');assert.equal(email.attachments[0].filename,'photo-1.jpg');assert.equal((await worker.fetch(req(),{...sending,EMAIL:{send:async()=>{throw new Error('provider');}}} as any)).status,502);}finally{globalThis.fetch=original;}});
test('quota rejection and quota outages never send mail',async()=>{const original=globalThis.fetch;let sent=0;try{globalThis.fetch=async()=>Response.json({success:true,hostname:'example.com',action:'quote'});for(const code of ['daily_limit','visitor_limit','outage']){const limited={...env,EMAIL:{send:async()=>{sent++;}},QUOTE_LIMITS:{getByName:()=>({reserve:async()=>{if(code==='outage')throw new Error('unavailable');return {ok:false,code,retryAfter:600};}})}};const response=await worker.fetch(req(),limited as any);assert.equal(response.status,code==='outage'?503:429);if(code!=='outage')assert.equal(response.headers.get('Retry-After'),'600');}assert.equal(sent,0);}finally{globalThis.fetch=original;}});
test('rejects changed recipient and missing visitor address',async()=>{assert.equal((await worker.fetch(req(),{...env,CONTACT_TO:'other@example.com'} as any)).status,503);const request=req();request.headers.delete('CF-Connecting-IP');assert.equal((await worker.fetch(request,env as any)).status,403);});

test('custom domain accepts its own challenge but rejects tokens from the other allowed host',async()=>{
 const original=globalThis.fetch;let sent=0;
 const multi={...env,TURNSTILE_HOSTNAME:'example.com,steliteprojects.com',EMAIL:{send:async()=>{sent++;}}};
 const custom=()=>{const source=req();return new Request('https://steliteprojects.com/api/quote',{method:'POST',headers:{Origin:'https://steliteprojects.com','CF-Connecting-IP':'192.0.2.1','Content-Type':source.headers.get('Content-Type')!},body:source.body,duplex:'half'} as RequestInit);};
 try{globalThis.fetch=async()=>Response.json({success:true,hostname:'steliteprojects.com',action:'quote'});assert.equal((await worker.fetch(custom(),multi as any)).status,200);assert.equal(sent,1);
 globalThis.fetch=async()=>Response.json({success:true,hostname:'example.com',action:'quote'});assert.equal((await worker.fetch(custom(),multi as any)).status,403);assert.equal(sent,1);
 const foreign=new Request('https://evil.example/api/quote',{method:'POST',headers:{Origin:'https://evil.example'},body:new FormData()});assert.equal((await worker.fetch(foreign,multi as any)).status,403);
 }finally{globalThis.fetch=original;}
});
