/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/env.d.ts` (hash: 3fe3ec94d65a01fd5cf01d02e77c4e33)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	QUOTES_ENABLED: "true";
	CONTACT_TO: "steliteprojects@gmail.com";
	MAIL_FROM: "devis@forms.steliteprojects.com";
	TURNSTILE_HOSTNAME: "steliteprojects.com,steliteprojects-web.cristian-sandu-connect.workers.dev";
	QUOTE_LIMITS: DurableObjectNamespace<import("./index").QuoteLimits>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "QuoteLimits";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "QUOTES_ENABLED" | "CONTACT_TO" | "MAIL_FROM" | "TURNSTILE_HOSTNAME">> {}
}
